version: '3'
services:
  bull-monitor:
    image: bull-monitor-test:latest
    ports:
      - 3000:3000
    environment:
      UI: bull-board
      REDIS_HOST: master.beti-sandbox.69ngmp.euw1.cache.amazonaws.com
      REDIS_PORT: 6379
      REDIS_PASSWORD: "]r<{y[J]h7I{s{1NOK}{!XymlBC0f!m{aRA<LS[H"
      BULL_WATCH_QUEUE_PREFIXES: "bull"
      LOG_LEVEL: "info"
      PORT: 3000
      REDIS_ENABLE_TLS: "true"